name: '- Reusable - Publish Package'
on:
  workflow_call:
    inputs:
      package-path:
        description: 'Path to the package'
        required: true
        type: string
    secrets:
      npm-token:
        required: true
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Install dependencies and build
        run: |
          cd ${{ inputs.package-path }}
          pnpm install
          if [ -n "$(node -e "console.log(require('./package.json').scripts?.build || '')")" ]; then
            pnpm run build
          fi

      - name: Bump package version and push to main
        run: |
          git config user.name "Bob Obringer"
          git config user.email "bob@obringer.net"
          git checkout main
          git pull
          cd ${{ inputs.package-path }}
          pnpm version patch -m "bump version [ci skip]"
          git add .
          git commit -m "Bump version [ci skip]"
          for i in {1..5}; do
            git push origin main && break
            echo "Attempt $i failed, retrying in 15 seconds..."
            sleep 2
            git pull origin main
          done

      - name: Check Git status
        run: git status

      - name: Publish
        run: |
          cd ${{ inputs.package-path }}
          git fetch
          git checkout main
          git pull
          pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}

      - name: Sync to Develop
        run: |
          git config user.name "Bob Obringer"
          git config user.email "bob@obringer.net"
          git checkout main
          git pull
          git fetch
          git checkout develop
          git pull
          git merge main --no-ff -m "Sync version bump back into develop [ci skip]"
          git push
