name: Changeset
on:
  pull_request:
    branches:
      - main

jobs:
  create-changeset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.0
      - name: Install dependencies
        run: pnpm install
      - name: Create Changeset
        run: |
          if pnpm changeset status --since=origin/main; then
            echo "Skipping changeset creation, no changes detected"
          else
            pnpm changeset version
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add .
            git commit -m "chore: create changeset"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
