name: Generate Changeset

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  generate-changeset:
    runs-on: ubuntu-latest
    env:
      FONTAWESOME_NPM_TOKEN: ${{ secrets.FONTAWESOME_NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Build @bob-obringer/conventional-changesets
        run: pnpx turbo run build --filter=@bob-obringer/conventional-changesets

      - name: Fetch origin
        run: |
          git checkout main
          git fetch
          git checkout develop

      - name: Run @bob-obringer/conventional-changesets
        run: |
          pnpm install
          ./node_modules/.bin/generate-changeset
        
      - name: Add changeset to PR
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .changeset
          # Check if there are changes to commit
          if git diff-index HEAD; then
            echo "Committing changes"
            git commit -m 'ci: update changeset [skip vercel ci]'
            git push
          else
            echo "No changes to commit"
          fi        
