name: Changeset Generation

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  generate-changeset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: List branches
        run: git branch --all
        
      - name: Checkout main branch
        run: git checkout main  
        
      - name: Fetch latest changes
        run: git fetch origin
        
      - name: Checkout pull request merge commit
        run: git checkout ${{ github.sha }}

      - name: Build conventional-changeset
        run: pnpx turbo run build --scope=@bob-obringer/conventional-changeset

      - name: Run changeset generation
        run: node public-packages/conventional-changeset/dist/cli.js

#      - name: Install GitHub CLI
#        run: |
#          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
#          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
#          sudo apt update
#          sudo apt install gh

      - name: Add changeset to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .changeset
          git commit -m 'ci: eUpdate changeset'
          git push
          
          
#          git checkout -b changeset-update
          
#          gh pr edit ${{ github.event.pull_request.number }} --body "$(cat .changeset/*.md)"