name: Release
on:
  push:
    branches:
      - main

jobs:
  changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install

      - name: Publish Packages
        run: |
          pnpm recursive exec --filter "./packages/*" -- '
            package_name=$(jq -r ".name" package.json)
            package_version=$(jq -r ".version" package.json)
            if [ -n "$package_name" ]; then
              if ! npm view "$package_name@$package_version" > /dev/null 2>&1; then
                npm publish --access public
              else
                echo "Skipping publish for $package_name@$package_version (already exists)"
              fi
            else
              echo "Skipping publish for $(pwd) (missing package name)"
            fi
          '
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
      - name: Create Changeset
        run: |
          if pnpm changeset status --since=origin/main; then
            echo "Skipping changeset creation, no changes detected"
          else
            pnpm changeset version
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add .
            git commit -m "chore: create changeset"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install

      - name: Create Release Pull Request
        uses: changesets/action@v1
        id: changesets
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Enable Pull Request Automerge
        if: steps.changesets.outputs.publishedPackages
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.changesets.outputs.pullRequestNumber }}
          merge-method: squash

  merge-back:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Merge main into develop
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout develop
          git merge --no-ff main
          git push origin develop
